name: 🔧 リファクタリング
description: コードの改善・リファクタリングの提案
title: "[Refactor] "
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        コードの改善やリファクタリングに関する提案をお聞かせください。
        品質向上、保守性向上、パフォーマンス改善などの観点からご提案をお待ちしています。

  - type: textarea
    id: overview
    attributes:
      label: 📋 リファクタリング概要
      description: 改善したい内容を具体的に説明してください
    validations:
      required: true

  - type: checkboxes
    id: purpose
    attributes:
      label: 🎯 目的
      description: 該当する目的を選択してください（複数選択可）
      options:
        - label: パフォーマンス改善
        - label: 可読性向上
        - label: 重複コード削除
        - label: 技術的負債の解消
        - label: テストカバレッジ向上
        - label: セキュリティ強化

  - type: input
    id: other_purpose
    attributes:
      label: その他の目的
      description: 上記以外の目的がある場合は記入してください

  - type: textarea
    id: target_location
    attributes:
      label: 📍 対象箇所
      description: ファイルパスや関数名など、具体的な対象箇所を記入してください
      placeholder: |
        例：
        - src/components/ReceiptForm.tsx
        - src/lib/api/notion.ts
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 🔧 改善案
      description: 具体的なアプローチや実装方法を説明してください
    validations:
      required: true

  - type: textarea
    id: impact_scope
    attributes:
      label: ⚠️ 影響範囲
      description: このリファクタリングで影響を受ける機能や部分を記載してください

  - type: checkboxes
    id: completion_criteria
    attributes:
      label: ✅ 完了条件
      description: 完了とみなす条件を選択してください（複数選択可）
      options:
        - label: コードの改善完了
        - label: 既存テストがすべてパス
        - label: 新規テストの追加（必要に応じて）
        - label: パフォーマンス計測実施（必要に応じて）
        - label: コードレビュー完了
        - label: ドキュメント更新